!GCD OF TWO NUMBERS
PROGRAM GCD_NOS
 IMPLICIT NONE
 INTEGER::NO1,NO2,I,J,GCD=1,TEMP,FACT
 PRINT*,"ENTER FIRST NO"
  READ*,NO1
 PRINT*,"ENTER SECOND NO"
  READ*,NO2
J=SQRT(REAL(NO1))*SQRT(REAL(NO2))
DO I=1,J
 IF(MOD(NO1,I)==0 .AND. MOD(NO2,I) == 0 )THEN
   NO1=NO1/I
   NO2=NO2/I
   GCD =GCD*I
 ENDIF
END DO

PRINT*,"RESULT","GCD=",GCD
END PROGRAM GCD_NOS
